name: Post to Google Sheet

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  post-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save GitHub event to file
        run: |
          mkdir -p tmp
          echo '${{ toJSON(github.event) }}' > event.json

      - name: Build payload
        id: build
        run: |
          set -euo pipefail
          EVENT_NAME="${{ github.event_name }}"
          echo "Event: $EVENT_NAME" >&2

          actor="${{ github.actor }}"
          repo="${{ github.repository }}"
          ref="${{ github.ref }}"

          if [ "$EVENT_NAME" = "push" ]; then
            commit_msg=$(jq -r '.head_commit.message // ""' event.json)
            url=$(jq -r '.head_commit.url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "push" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              --arg ref "$ref" \
              --arg message "$commit_msg" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, message:$message, url:$url}')
          
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            title=$(jq -r '.pull_request.title // ""' event.json)
            url=$(jq -r '.pull_request.html_url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "pull_request" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              --arg ref "$ref" \
              --arg title "$title" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, title:$title, url:$url}')
          
          elif [ "$EVENT_NAME" = "release" ]; then
            name=$(jq -r '.release.name // ""' event.json)
            url=$(jq -r '.release.html_url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "release" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              --arg ref "$ref" \
              --arg name "$name" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, name:$name, url:$url}')
          
          else
            PAYLOAD=$(jq -n '{event_type:"other"}')
          fi

          # Escape for GitHub Actions output
          escaped_payload=$(echo "$PAYLOAD" | sed 's/%/%25/g; s/\r/%0D/g; s/\n/%0A/g')
          echo "payload=$escaped_payload" >> "$GITHUB_OUTPUT"

      - name: Post to Google Sheet
        run: |
          set -euo pipefail
          echo "Posting payload to Google Sheet..." >&2
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "x-sheet-secret: $SHEET_SECRET" \
            -d '${{ steps.build.outputs.payload }}' \
            "$SHEET_URL"
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SHEET_SECRET: ${{ secrets.SHEET_SECRET }}
