name: Push GitHub activity to Google Sheet

on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  post-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl coreutils

      - name: Build payload
        id: build
        run: |
          set -euo pipefail
          EVENT_NAME="${{ github.event_name }}"
          echo "Event: $EVENT_NAME" >&2

          if [ "$EVENT_NAME" = "push" ]; then
            actor="${{ github.actor }}"
            repo="${{ github.repository }}"
            ref="${{ github.ref }}"
            commit_msg=$(jq -r '.head_commit.message // ""' <<< '${{ toJson(github.event) }}')
            url=$(jq -r '.head_commit.url // ""' <<< '${{ toJson(github.event) }}')
            PAYLOAD=$(jq -n \
              --arg type "push" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              --arg ref "$ref" \
              --arg message "$commit_msg" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, message:$message, url:$url}')
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            pr_action=$(jq -r '.action // ""' <<< '${{ toJson(github.event) }}')
            pr_title=$(jq -r '.pull_request.title // ""' <<< '${{ toJson(github.event) }}')
            pr_url=$(jq -r '.pull_request.html_url // ""' <<< '${{ toJson(github.event) }}')
            actor="${{ github.actor }}"
            repo="${{ github.repository }}"
            PAYLOAD=$(jq -n \
              --arg type "pull_request" \
              --arg action "$pr_action" \
              --arg title "$pr_title" \
              --arg url "$pr_url" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              '{event_type:$type, action:$action, actor:$actor, repo:$repo, message:$title, url:$url}')
          elif [ "$EVENT_NAME" = "release" ]; then
            tag=$(jq -r '.release.tag_name // ""' <<< '${{ toJson(github.event) }}')
            url=$(jq -r '.release.html_url // ""' <<< '${{ toJson(github.event) }}')
            actor="${{ github.actor }}"
            repo="${{ github.repository }}"
            PAYLOAD=$(jq -n \
              --arg type "release" \
              --arg tag "$tag" \
              --arg url "$url" \
              --arg actor "$actor" \
              --arg repo "$repo" \
              '{event_type:$type, tag:$tag, actor:$actor, repo:$repo, url:$url}')
          else
            PAYLOAD=$(jq -n '{event_type:"other"}')
          fi

          # base64-encode safely for cross-step transport
          PAYLOAD_B64=$(printf '%s' "$PAYLOAD" | base64 -w0)
          {
            echo "payload_b64=$PAYLOAD_B64"
          } >> "$GITHUB_OUTPUT"

      - name: POST to Google Sheet Apps Script (safe decode & follow redirects)
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SHEET_SECRET: ${{ secrets.SHEET_SECRET }}
        run: |
          set -euo pipefail
          echo "Decoding payload and posting to sheet..." >&2

          # decode base64 payload into tmp file (safe: no quoting issues)
          echo "${{ steps.build.outputs.payload_b64 }}_
