name: Post to Google Sheet

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  post-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save GitHub event to file
        run: |
          mkdir -p tmp
          echo '${{ toJSON(github.event) }}' > event.json

      - name: Build payload and post
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          SHEET_SECRET: ${{ secrets.SHEET_SECRET }}
          EVENT_NAME: ${{ github.event_name }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          REF: ${{ github.ref }}
        run: |
          set -euo pipefail
          echo "Event: $EVENT_NAME" >&2

          if [ "$EVENT_NAME" = "push" ]; then
            commit_msg=$(jq -r '.head_commit.message // ""' event.json)
            url=$(jq -r '.head_commit.url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "push" \
              --arg actor "$ACTOR" \
              --arg repo "$REPO" \
              --arg ref "$REF" \
              --arg message "$commit_msg" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, message:$message, url:$url}')

          elif [ "$EVENT_NAME" = "pull_request" ]; then
            title=$(jq -r '.pull_request.title // ""' event.json)
            url=$(jq -r '.pull_request.html_url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "pull_request" \
              --arg actor "$ACTOR" \
              --arg repo "$REPO" \
              --arg ref "$REF" \
              --arg title "$title" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, title:$title, url:$url}')

          elif [ "$EVENT_NAME" = "release" ]; then
            name=$(jq -r '.release.name // ""' event.json)
            url=$(jq -r '.release.html_url // ""' event.json)
            PAYLOAD=$(jq -n \
              --arg type "release" \
              --arg actor "$ACTOR" \
              --arg repo "$REPO" \
              --arg ref "$REF" \
              --arg name "$name" \
              --arg url "$url" \
              '{event_type:$type, actor:$actor, repo:$repo, ref:$ref, name:$name, url:$url}')
          else
            PAYLOAD=$(jq -n '{event_type:"other"}')
          fi

          echo "Posting payload to Google Sheet..." >&2
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "x-sheet-secret: $SHEET_SECRET" \
            -d "$PAYLOAD" \
            "$SHEET_URL"
