name: Push GitHub activity to Google Sheet

on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  post-to-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl coreutils

      - name: Build payload
        id: build
        run: |
          set -euo pipefail
          EVENT_NAME="${{ github.event_name }}"
          echo "Event: $EVENT_NAME" >&2

          EVENT_JSON='${{ toJson(github.event) }}'
          actor="${{ github.actor }}"
          repo="${{ github.repository }}"
          ref="${{ github.ref }}"

          PAYLOAD=$(jq -n '{event_type:"other"}')

          if [ "$EVENT_NAME" = "push" ]; then
            commit_msg=$(jq -r '.head_commit.message // ""' <<< "$EVE
